jobs:
  include:
    - stage: build image
      script:
        - ./image.sh build
      after_success:
        - if [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
          ./image.sh push;
          fi
